### ISSUE TITLE
sbank issue v0.0.3

### ISSUE THREAD

**Issue by MariaAssiduo** [gwastro/sbank#38]
Hi. I use since last year sbank v0.03 but never encountered the following error before:

```
  File "/home/maria.assiduo/gwastro4/sbank_Python3/lib/python3.6/site-packages/ligo/lw/ligolw.py", line 911, in startElementNS
    raise type(e)("line %d: %s" % (self._locator.getLineNumber(), str(e)))
ligo.lw.ligolw.ElementError: line 39: invalid type 'ilwd:char' for Column 'event_id' in Table 'sngl_inspiral', expected type 'int_8s'
```

I can't figure out how could change the type ilwd:char in int_8s. How to fix it? Thanks in advance.

**Comment by spxiwh** [comment]
@MariaAssiduo This looks like an issue related to the move from the deprecated glue.ligolw to the new ligo.lw (which as you've seen, has caused a few things we're trying to fix).

Is it the case here that you have an *input* xml file that is in the old format? If so I quote from an email from Kipp about how to deal with this:

```
The ID column type was changed from strings containing table and column names to just plain integers.  A tool is available to translate old-format files to new-format files:

$ ligolw_no_ilwdchar filename1 filename2 ...

The files are converted in-place (they are overwritten) so keep backup copies if you need to retain the originals.  There is no tool available to perform the inverse conversion.  The forward conversion is lossy, so without knowledge of the meaning of the file contents it's not possible to automatically reconstruct the metadata that was removed from the IDs.
```

The idea being to convert the input file *before* using it in sbank (make sure to make a backup of the file before running this though!)

**Comment by MariaAssiduo** [comment]
@spxiwh Hi, sorry for late reply. Actually no, there is no imput file. It's a template bank with an empty seed. You can have a look in the directory on CIT /home/maria.assiduo/NEW_TB/TB_50-300/hom/. Its failing only the very last node giving the aforementioned error, so I am not sure how to resolve the problem.
Thank you.

**Comment by MariaAssiduo** [comment]
@spxiwh Thank you. Then, I have to build the template bank with the latest sbank version, in order to have the bank in the  new format XML file. But, if I use the waveforms SEOBNRv4HM_ROM, I still have problems that is not found the file hdf5 in LAL_DATA_PATH=/home/cbc/ROM_data. My directory on CIT with this test is /home/maria.assiduo/test_gwastro6/test_seobHM_50-500/


XLAL Error - SEOBNRv4HMROM_Init_LALDATA (LALSimIMRSEOBNRv4HMROM.c:447): Unable to resolve data file SEOBNRv4HMROM.hdf5 in $LAL_DATA_PATH

```
XLAL Error - SEOBNRv4HMROM_Init_LALDATA (LALSimIMRSEOBNRv4HMROM.c:447): I/O error
XLAL Error - SEOBNRv4HMROM_freq_phase_sparse_grid_hybrid (LALSimIMRSEOBNRv4HMROM.c:889): Error setting up SEOBNRv4ROM data - check your $LAL_DATA_PATH

XLAL Error - SEOBNRv4HMROM_freq_phase_sparse_grid_hybrid (LALSimIMRSEOBNRv4HMROM.c:889): Generic failure
XLAL Error - SEOBNRv4HMROMCoreModeAmpPhaseSplines (LALSimIMRSEOBNRv4HMROM.c:1511): Internal function call failed: Generic failure
XLAL Error - SEOBNRv4HMROMCoreModesHybridized (LALSimIMRSEOBNRv4HMROM.c:2285): Internal function call failed: Generic failure
XLAL Error - XLALSimIMRSEOBNRv4HMROM (LALSimIMRSEOBNRv4HMROM.c:2604): Internal function call failed: Generic failure
XLAL Error - XLALSimInspiralChooseFDWaveform (LALSimInspiral.c:2357): Internal function call failed: Generic failure
Traceback (most recent call last):
  File "/home/maria.assiduo/gwastro6/sbank_Python3/bin/sbank", line 543, in <module>
    match, matcher = bank.covers(tmplt, opts.match_min)
  File "/home/maria.assiduo/gwastro6/sbank_Python3/lib/python3.9/site-packages/sbank/bank.py", line 219, in covers
    match = self.compute_match(tmplt, proposal,
  File "/home/maria.assiduo/gwastro6/sbank_Python3/lib/python3.9/site-packages/sbank/bank.py", line 165, in _brute_match
    match = tmplt.brute_match(proposal, f, self._workspace_cache, **kwargs)
  File "/home/maria.assiduo/gwastro6/sbank_Python3/lib/python3.9/site-packages/sbank/waveforms.py", line 990, in brute_match
    hp, hc, hphccorr = self.get_whitened_normalized_comps(df, **kwargs)
  File "/home/maria.assiduo/gwastro6/sbank_Python3/lib/python3.9/site-packages/sbank/waveforms.py", line 754, in get_whitened_normalized_comps
    hp, hc = self._compute_waveform_comps(df, self.f_final)
  File "/home/maria.assiduo/gwastro6/sbank_Python3/lib/python3.9/site-packages/sbank/waveforms.py", line 716, in _compute_waveform_comps
    hplus_fd, hcross_fd = lalsim.SimInspiralChooseFDWaveform(
RuntimeError: Internal function call failed: Generic failure
```

Thank you in advance if you may have any suggestions.

**Comment by spxiwh** [comment]
@MariaAssiduo The data files in `/home/cbc/ROM_data` on CIT were out of date. I've just updated them now, so hopefully this failure should go away.
