### ISSUE TITLE
sbank v1.0.2 error

### ISSUE THREAD

**Issue by MariaAssiduo** [gwastro/sbank#49]
Hi, I'm trying to run the latest version of sbank (I have a copy of it in my CIT home directory) and I encountered the following error:

```
Traceback (most recent call last):
  File "/home/maria.assiduo/gwastro8/sbank_Python3/bin/sbank_pipe", line 304, in <module>
    sbankJob = SBankJob(cp, tag_base=options.user_tag + "_sbank")
  File "/home/maria.assiduo/gwastro8/sbank_Python3/bin/sbank_pipe", line 91, in __init__
    inspiral.InspiralAnalysisJob.__init__(self,cp,sections,exec_name,extension)
  File "/home/maria.assiduo/gwastro8/sbank_Python3/lib/python3.6/site-packages/lalapps/inspiral.py", line 46, in __init__
    pipeline.AnalysisJob.__init__(self,cp,dax)
TypeError: __init__() takes 2 positional arguments but 3 were given
(sbank_Python3) [maria.assiduo@ldas-pcdev5 bank_SEOBPHM]$ sbank_pipe --config-file sbank_seobphm.ini --user-tag sbank_seobphm
Traceback (most recent call last):
  File "/home/maria.assiduo/gwastro8/sbank_Python3/bin/sbank_pipe", line 304, in <module>
    sbankJob = SBankJob(cp, tag_base=options.user_tag + "_sbank")
  File "/home/maria.assiduo/gwastro8/sbank_Python3/bin/sbank_pipe", line 91, in __init__
    inspiral.InspiralAnalysisJob.__init__(self,cp,sections,exec_name,extension)
  File "/home/maria.assiduo/gwastro8/sbank_Python3/lib/python3.6/site-packages/lalapps/inspiral.py", line 46, in __init__
    pipeline.AnalysisJob.__init__(self,cp,dax)
TypeError: __init__() takes 2 positional arguments but 3 were given
```

Any suggestion? Thanks in advance.

**Comment by duncanmmacleod** [comment]
@MariaAssiduo, you need to update to the latest version of `lalapps`, I think.

**Comment by MariaAssiduo** [comment]
@duncanmmacleod thanks, but I get the following error:

```
(sbank_Python3) [maria.assiduo@ldas-pcdev5 lalsuite]$ pip install --upgrade lalsuite
Requirement already satisfied: lalsuite in /home/maria.assiduo/gwastro8/sbank_Python3/lib/python3.6/site-packages (7.0)
Requirement already satisfied: lscsoft-glue in /home/maria.assiduo/gwastro8/sbank_Python3/lib/python3.6/site-packages (from lalsuite) (3.0.1)
Requirement already satisfied: python-dateutil in /home/maria.assiduo/gwastro8/sbank_Python3/lib/python3.6/site-packages (from lalsuite) (2.8.2)
Requirement already satisfied: ligo-segments in /home/maria.assiduo/gwastro8/sbank_Python3/lib/python3.6/site-packages (from lalsuite) (1.4.0)
Requirement already satisfied: matplotlib in /home/maria.assiduo/gwastro8/sbank_Python3/lib/python3.6/site-packages (from lalsuite) (3.3.4)
Requirement already satisfied: numpy>=1.7 in /home/maria.assiduo/gwastro8/sbank_Python3/lib/python3.6/site-packages (from lalsuite) (1.19.5)
Requirement already satisfied: importlib-resources in /home/maria.assiduo/gwastro8/sbank_Python3/lib/python3.6/site-packages (from lalsuite) (5.4.0)
Requirement already satisfied: scipy in /home/maria.assiduo/gwastro8/sbank_Python3/lib/python3.6/site-packages (from lalsuite) (1.5.4)
Requirement already satisfied: zipp>=3.1.0 in /home/maria.assiduo/gwastro8/sbank_Python3/lib/python3.6/site-packages (from importlib-resources->lalsuite) (3.6.0)
Requirement already satisfied: six in /home/maria.assiduo/gwastro8/sbank_Python3/lib/python3.6/site-packages (from ligo-segments->lalsuite) (1.16.0)
Requirement already satisfied: pyOpenSSL in /home/maria.assiduo/gwastro8/sbank_Python3/lib/python3.6/site-packages (from lscsoft-glue->lalsuite) (22.0.0)
Requirement already satisfied: pyRXP in /home/maria.assiduo/gwastro8/sbank_Python3/lib/python3.6/site-packages (from lscsoft-glue->lalsuite) (3.0.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/maria.assiduo/gwastro8/sbank_Python3/lib/python3.6/site-packages (from matplotlib->lalsuite) (1.3.1)
Requirement already satisfied: pillow>=6.2.0 in /home/maria.assiduo/gwastro8/sbank_Python3/lib/python3.6/site-packages (from matplotlib->lalsuite) (8.4.0)
Requirement already satisfied: cycler>=0.10 in /home/maria.assiduo/gwastro8/sbank_Python3/lib/python3.6/site-packages (from matplotlib->lalsuite) (0.11.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in /home/maria.assiduo/gwastro8/sbank_Python3/lib/python3.6/site-packages (from matplotlib->lalsuite) (3.0.9)
Requirement already satisfied: cryptography>=35.0 in /home/maria.assiduo/gwastro8/sbank_Python3/lib/python3.6/site-packages (from pyOpenSSL->lscsoft-glue->lalsuite) (37.0.2)
Requirement already satisfied: cffi>=1.12 in /home/maria.assiduo/gwastro8/sbank_Python3/lib/python3.6/site-packages (from cryptography>=35.0->pyOpenSSL->lscsoft-glue->lalsuite) (1.15.0)
Requirement already satisfied: pycparser in /home/maria.assiduo/gwastro8/sbank_Python3/lib/python3.6/site-packages (from cffi>=1.12->cryptography>=35.0->pyOpenSSL->lscsoft-glue->lalsuite) (2.21)
(sbank_Python3) [maria.assiduo@ldas-pcdev5 lalsuite]$ pip install --upgrade lalapps
ERROR: Could not find a version that satisfies the requirement lalapps (from versions: none)
ERROR: No matching distribution found for lalapps
```
